name: skycast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  geolocator: ^13.0.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.3.0+1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  auto_route_generator: ^9.3.1

flutter:

  uses-material-design: true

  assets:
   - .env